codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    project:
      default:
        target: auto
        threshold: 0.2%
        base: auto
    patch:
      default:
        target: auto
        threshold: 0%
        base: auto
    changes: false

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, reach, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "src/Lists"
  - "src/PHPDocs"
  - "src/MoneyServiceProvider.php"
  - "src/helpers.php"
